[package]
name = "tdl-rs"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "tdl"
path = "src/main.rs"

[dependencies]
color-eyre =  "~0.5"
env_logger = "~0.9"
log = "~0.4"
structopt = "~0.3"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"

[dev-dependencies]
assert_fs = "~1.0"
predicates = "~2.0"
