[package]
name = "test_helpers"
version = "0.1.0"
publish = false
license = "MIT OR BSD-3-Clause"
edition = "2018"

[dependencies]
color-eyre =  "~0.5"
chrono = { version = "~0.4", features = ["serde"] }
